#!/usr/bin/env escript
# escript work with shell script

# start system
main(["start"]) ->
	
# stop system
main(["stop"]) ->
	
# usage
main([]) ->
	usage().
	
usage() ->
	io:format("++++K++++++N++++++K++++~n"),
	io:format("This is the usage").

